CREATE TABLE pessoas (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    idade INT(3) NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
);